@extends('layouts.default')
@section('cabecera')
    @include('includes.cabecera')
@stop
@section('navegacion')
    @include('includes.navegacion')
@stop
@section('carrusel')
@include('includes.carrusel')
@stop
@section('contenido')
    @include('includes.contenido-home')
@stop
@section('footer')
    @include('includes.footer')
@stop